### ISSUE TITLE
ModuleNotFoundError: No module named "PIL"

### ISSUE THREAD

**Issue by digitalbarrito** [cff29546/pzmap2dzi#1]
trying to run this program and keep getting this :

> Unpacking textures ...
> Traceback (most recent call last):
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "D:\pzmap2dzi-main\pzmap2dzi\texture.py", line 2, in <module>
>     from PIL import Image
> ModuleNotFoundError: No module named 'PIL'
> Unpacking textures done
> Copy html files ...
> 47 File(s) copied
> Copy html files done
> Render top view pz map ...
> Traceback (most recent call last):
>   File "D:\pzmap2dzi-main\render_base_top.py", line 1, in <module>
>     from PIL import Image, ImageDraw, ImageFont
> ModuleNotFoundError: No module named 'PIL'
> Render top view pz map done
> Render top view zombie ...
> Traceback (most recent call last):
>   File "D:\pzmap2dzi-main\render_zombie_top.py", line 1, in <module>
>     from PIL import Image, ImageDraw, ImageFont
> ModuleNotFoundError: No module named 'PIL'
> Render top view zombie done
> Render top view foraging ...
> Traceback (most recent call last):
>   File "D:\pzmap2dzi-main\render_foraging_top.py", line 1, in <module>
>     from PIL import Image, ImageDraw, ImageFont
> ModuleNotFoundError: No module named 'PIL'
> Render top view foraging done
> All done

Not sure what I'm doing wrong, I have Python 3.10.5 installed, and ran the install_requirements.bat like instructed.

**Comment by digitalbarrito** [comment]
Update: While using Python 3.10.5, PIL is no longer supported out of the box, fixed the issue by installing Pillow.

**Comment by cff29546** [comment]
I have updated the requirements.txt to include pillow for Python 3.10.5+.
