### ISSUE TITLE
Not an issue, but very nice to have if someone is trying to build a modded map

### ISSUE THREAD

**Issue by ethano8225** [cff29546/pzmap2dzi#11]
Hey, I wanted to thank you for creating a mapping mod I could actually use, and provide the files I've used to create a full map for the "[Project Zomboid Maps](https://steamcommunity.com/sharedfiles/filedetails/?id=2968702010)" collection on steam. It consists of around 120 map mods and it took me around 8 hours to get this done, so it may be helpful to some in the future.

Thank you again, and if there is a better place I could put this, let me know 
(Also, feel free to have this as an example or whatever in the git itself. Everything runs cleanly after the 1st run, no missing files or anything)

https://pastebin.com/ATpygf2X <- conf.yaml
https://pastebin.com/Tm2FmK5q <- map_data.yaml

edit: i only tested this with the 2d map, not isometric, as my computer would be at like 0 storage if i did. feel free to test if isometric works

**Comment by cff29546** [comment]
Thank you for your hard work. I will merge the changes into the git repository after validating them.

**Comment by ethano8225** [comment]
Sounds good. I made a list of additions [here](https://pastebin.com/kmUL7Bwt)

**Comment by cff29546** [comment]
Good to know that.
Also you can make a push request to the https://github.com/cff29546/pzmap2dzi/blob/main/docs/tested_maps.md, and add some creadit to yourself in the change log.
