### ISSUE TITLE
[not issue] storage optimizations

### ISSUE THREAD

**Issue by nic0laz** [cff29546/pzmap2dzi#12]
Im trying to render the full map for the server where im playing, it haves, it haves 6 mod maps and im running out of storage (1.8T).

what can i do to "compress" the output?

at this moment im running it again with:
    layers: 5
    image_compress_level: 9
    omit_levels: 1
    vehicle: false
    special_zombie: false
    stroy: false
    plants_conf:
        # eable snow on trees and bushes
        snow: false
        # use large bushes
        large_bush: false
        # eable flower on trees and bushes
        flower: false
        # supported season: spring, summer, summer2, autumn, winter
        season: summer2
        # normal tree size, range from 0 to 3 (inclusive)
        tree_size: 0
        # large tree size, range from 0 to 5 (inclusive)
        jumbo_tree_size: 2
        # large tree type, from: 0 to 10  (inclusive)
        # see _TREE_DEF in pzmap2dzi/plants.py for more detail
        jumbo_tree_type: 0
        # disable ground cover grass
        no_ground_cover: false
        # use only one type of tree
        # supported values:
        # -1        trees not unified
        # 0 to 10   the unified tree type
        unify_tree_type: -1

what's     tile_size: 1024 and     top_view_square_size: 1?, like tile resolution?

thanks and awesome work!!!!

**Comment by cff29546** [comment]
just make sure you have `enable_cache: true` so that the `omit_levels: 1` can work correctly.
