### ISSUE TITLE
define max zoom level (to save storage)

### ISSUE THREAD

**Issue by Nightreaver** [cff29546/pzmap2dzi#22]
I was thinking, is it possible to set the max zoom level? 

my current max zoom level is ( lol )
![image](https://github.com/user-attachments/assets/a5b2501b-808e-4e1c-af94-4f5e5e959ef2)

I think for my purpose it would be enough to zoom in/out until 

![image](https://github.com/user-attachments/assets/14862660-4aae-4102-83e7-31b8309d8ed6)

Would it skip some render tiles or is it simple bitmap scaling to this point?
I feel like 300+gb for this map is a bit much

Is this achievable with "omit_levels" ? 

The explanation is not fully clear to me...
How many levels are there? 
If I omit 2 levels, how much "zoom" do I loose?
ect.

**Comment by cff29546** [comment]
"omit_levels" does just that. Setting "omit_levels = 1" saves approximately 75% of space by skipping the maximum zoom level.

**Comment by Nightreaver** [comment]
But the calculation of the tiles that will be generated does not reflect that?

**Comment by cff29546** [comment]
> But the calculation of the tiles that will be generated does not reflect that?

PZ only offers textures at the highest zoom level, so the rendering can only occur at that level. The levels that are omitted are removed after being thumbnailed for lower zoom levels to reduce disk size.

**Comment by Nightreaver** [comment]
It worked well.

been rendering with 

```
    omit_levels[default](base): 3
    omit_levels(base): 2
    omit_levels: 2
```

which is a quite good storage/quality ratio
