### ISSUE TITLE
Typo in config 'stroy'

### ISSUE THREAD

**Issue by Nightreaver** [cff29546/pzmap2dzi#23]
Im not sure what exactly this word means so im suspecting a typo, but there is also no reference to this word.

What does this do?

https://github.com/cff29546/pzmap2dzi/blob/main/conf/conf.yaml#L150

**Comment by cff29546** [comment]
Thanks. These are more than just typos; these flags are not working correctly. I have fixed these flags in this [commit](https://github.com/cff29546/pzmap2dzi/commit/44473fee84654dc56a4c202be3e46339f69cba92).
