### ISSUE TITLE
Receiving traceback error when running collect_mod_map_data.py

### ISSUE THREAD

**Issue by TheoBearDB** [cff29546/pzmap2dzi#27]
Hi there! Thanks for making this tool, it's fantastic! 

However, I'm running into an issue when trying to run the 'collect_mod_map_data.py' script. I don't know if it's just me being dumb and missing a step, but I've gone over the instructions a lot and can't find anything to help. 

I get this error:

```
PS [path] python collect_mod_map_data.py -g
Traceback (most recent call last):
  File "[path]\collect_mod_map_data.py", line 173, in <module>
    textures, maps = collect_info(args.conf)
  File "[path]\collect_mod_map_data.py", line 111, in collect_info
    mods = get_steam_conf(mod_root, steam_id)
  File "[path]\collect_mod_map_data.py", line 71, in get_steam_conf
    info = read_info(mod_info)
  File "[path]\collect_mod_map_data.py", line 38, in read_info
    for line in f:
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 117: character maps to <undefined>

```

Not sure what's happening, but any help is appreciated! I'd love to use the script to get all the mod maps!

**Comment by cff29546** [comment]
It seems that you have a mod whose information file is not in English. Could you please share your mod list so that I can help you address this issue properly? 
If your Steam library is located at `D:\SteamLibrary`, you can open a command prompt and execute the following command. Then, please paste the output here:
```
dir /b D:\SteamLibrary\steamapps\workshop\content\108600\
```

**Comment by TheoBearDB** [comment]
Ah that seemed to do the trick! Thanks so much! <3

**Comment by cff29546** [comment]
Thank you for the information. I'll mark this one done.
