### ISSUE TITLE
A worker is stuck every time there is a error rendering

### ISSUE THREAD

**Issue by pimenta1807** [cff29546/pzmap2dzi#3]
I'm rendering a map collection from workshop and as far as i know, the map autor has used non utf-8 characteres in the room name, bringing this error.
![image](https://user-images.githubusercontent.com/86393537/205012318-bf6e70ad-973f-4b16-8d3b-01b0d904a7c2.png)

Every time it happens, i lost an worker until there is no one left (frezze)

Rendering only the top I found the "faulty" chunks (since they didn't render) and removed them from the project, however I think it would be very useful for the worker to abandon the rendering in case of failure.

**Comment by pimenta1807** [comment]
![image](https://user-images.githubusercontent.com/86393537/205018926-6ec8c675-a77e-4f84-a744-f90083c01196.png)
First top rendering, stuck in 3 chunks.

Was able to found the faulty ones, 
![image](https://user-images.githubusercontent.com/86393537/205019666-2b845edd-c206-4a3b-96c9-c9e4b9fcc48e.png)

Here they are in case you want to see
[maps.zip](https://github.com/cff29546/pzmap2dzi/files/10131194/maps.zip)

**Comment by cff29546** [comment]
added support for room name encoding [commit](https://github.com/cff29546/pzmap2dzi/commit/19398b492e68ad536e9589ad73c41569750b2749)

**Comment by cff29546** [comment]
Added task retry and error handling. See [commit](https://github.com/cff29546/pzmap2dzi/commit/b046b23daa327cb6319f3ed9155caa6c1dbc0011)
