### ISSUE TITLE
Many missing tile warning. missing interiors and tiles.

### ISSUE THREAD

**Issue by verdra** [cff29546/pzmap2dzi#4]
when running i receive a lot of missing tile warning during the base and base_top steps. after the process completes the map has a number of black regions in both top and isometric. the black regions are primarily in interiors, water, and field tiles.

there is also missing images for some chunks of the most zoomed out regions.

missing tile: blends_street_01_85
missing tile: blends_street_01_80
missing tile: blends_street_01_87
missing tile: blends_street_01_80
missing tile: blends_street_01_87
missing tile: blends_grassoverlays_01_16
missing tile: blends_street_01_86
missing tile: blends_grassoverlays_01_16

![pzmap_error_0](https://user-images.githubusercontent.com/26660627/233154544-d7fa74e3-fa80-450b-9fe4-3fc38113cdcd.png)

![pzmap_error_1](https://user-images.githubusercontent.com/26660627/233155039-0b1e6afa-8ffb-429d-92e1-4613c116ca59.png)

**Comment by cff29546** [comment]
Also, how much free memory do you have on your computer?
A typical 16 render threads setting will use about 16GB of memory. Tiles may not be able to load when you run out of memory.
You can follow the instructions on the readme file to use fewer render threads, and that will reduce the memory needed.

**Comment by verdra** [comment]
No missing textures or errors. i got that many jobs as well, which i assume corresponds to textures.

i have 64 GB of ram so thats not a problem

**Comment by cff29546** [comment]
I just [fixed a bug](https://github.com/cff29546/pzmap2dzi/commit/203280b3871a1d494a8bfe952a83de84da8e7c67) that may cause the missing tile error. Can you try the latest code and see if the problem still exists?

**Comment by verdra** [comment]
ok running base over again and its looking good so far, let you know how it goes. had to increase my ulimit to get it to run.

**Comment by verdra** [comment]
also i am running on linux. i converted some of the batch scripts to python. 

would you be open to PRs to convert the project to pure python to be more portable?

**Comment by cff29546** [comment]
> also i am running on linux. i converted some of the batch scripts to python.
> 
> would you be open to PRs to convert the project to pure python to be more portable?

I'm OK with PRs. The batch scripts are barely passing parameters to main entries. It is possible to add similar bash scripts for Linux support. Also, be aware that some libraries behave differently between Linux and Windows. For example, the shared_memory in Windows does not need unlink() to fully release as the OS does the clean-up when the last process closes the handle, but not calling unlink() accordingly on Linux will lead to a memory leak.

**Comment by verdra** [comment]
looks like it worked.
